### ISSUE TITLE
swoole Version => 4.6.7 兼容

### ISSUE THREAD

**Issue by xieyuhua** [Yurunsoft/YurunHttp#17]
swoole  Version => 4.6.7

PHP Deprecated:  Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown on line 0

Deprecated: Swoole\Event::rshutdown(): Event::wait() in shutdown function is deprecated in Unknown on line 0

**Comment by Yurunsoft** [comment]
YurunHttp 本身不控制协程的启动和等待，建议自行检查项目代码编写是否符合 Swoole 的标准
