### ISSUE TITLE
无法指定请求host ip

### ISSUE THREAD

**Issue by titrxw** [Yurunsoft/YurunHttp#8]
https://github.com/Yurunsoft/YurunHttp/blob/511bd99829e0df54acbd93d4bcf44be14d3e44e5/src/YurunHttp/Handler/Swoole.php#L176

这里应该先获取外部设置的host

**Comment by Yurunsoft** [comment]
已经修复，感谢反馈

**Comment by titrxw** [comment]
大概啥时候发布新版?

**Comment by Yurunsoft** [comment]
马上发布，正打算这两天发个版本呢
